import {
    FETCH_ITEMS,
    ADD_ITEM,
    REMOVE_ITEM,
    UPDATE_ITEM,
    EQUIP_ITEM,
    UNEQUIP_ITEM,
    OPEN_CONTAINER,
    CLOSE_CONTAINER,
    EMPTY_CONTAINER,
    INSPECT_ITEM,
} from './InventoryTypes'

