export const GET_PLAYER_INVENTORY = "GET_PLAYER_INVENTORY";

export const ADD_ITEM = "ADD_ITEM";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const EQUIP_ITEM = "EQUIP_ITEM";
export const UNEQUIP_ITEM = "UNEQUIP_ITEM";
export const MOVE_ITEM = "MOVE_ITEM";
export const INSPECT_ITEM = "INSPECT_ITEM";
export const OPEN_CONTAINER = "OPEN_CONTAINER";
export const CLOSE_CONTAINER = "CLOSE_CONTAINER";
export const EMPTY_CONTAINER = "EMPTY_CONTAINER";
export const SORT_INVENTORY = "SORT_INVENTORY";
export const SEARCH_INVENTORY = "SEARCH_INVENTORY";
export const FILTER_INVENTORY = "FILTER_INVENTORY";
export const SELECT_ITEM = "SELECT_ITEM";
export const DESELECT_ITEM = "DESELECT_ITEM";
