export const GET_PLAYER_INVENTORY = "GET_PLAYER_INVENTORY";
export const EQUIP_ITEM = "EQUIP_ITEM";
export const UNEQUIP_ITEM = "UNEQUIP_ITEM";
export const INSPECT_ITEM = "INSPECT_ITEM";
export const OPEN_CONTAINER = "OPEN_CONTAINER";
export const CLOSE_CONTAINER = "CLOSE_CONTAINER";
export const EMPTY_CONTAINER = "EMPTY_CONTAINER";
export const SEARCH_INVENTORY = "SEARCH_INVENTORY";

