export const GET_PLAYER_INVENTORY = "GET_PLAYER_INVENTORY";
export const EQUIP_ITEM = "EQUIP_ITEM";
export const UNEQUIP_ITEM = "UNEQUIP_ITEM";
export const SET_SOURCE = "SET_SOURCE";
export const SET_ITEM = "SET_ITEM";
export const SET_DESTINATION = "SET_DESTINATION";
export const EMPTY_CONTAINER = "EMPTY_CONTAINER";
export const SEARCH_INVENTORY = "SEARCH_INVENTORY";

